import type { MetadataRoute } from 'next'
import { SITE_URL } from '@/lib/site'

/**
 * Robots policy. Marketing pages are crawlable; private app surfaces, auth
 * pages, the admin panel, and API routes are kept out of the index.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin',
          '/admin/',
          '/dashboard',
          '/portal',
          '/clients',
          '/projects',
          '/meetings',
          '/tasks',
          '/payments',
          '/billing',
          '/settings',
          '/team',
          '/teammate',
          '/onboarding',
          '/login',
          '/signup',
          '/team-login',
          '/auth',
          '/diagnostics',
        ],
      },
    ],
    // profiles-sitemap.xml is generated by the app (business pages + marketplace)
    // and proxied here — see the rewrites in next.config.js.
    sitemap: [`${SITE_URL}/sitemap.xml`, `${SITE_URL}/profiles-sitemap.xml`],
    host: SITE_URL,
  }
}
